### ISSUE TITLE
It's empty

### ISSUE THREAD

**Issue by Diohicham** [Diohicham/sport_analysis#1]
Hi Hicham,

@diohicham28 
Start by reading some data, data types, 
statistical review, some correlation , some visualization

**Comment by Diohicham** [comment]
Hi Dioury,

I'm on it.
Did you look @ issue #2 on that project

**Comment by diohicham28** [comment]
> Hi Dioury,
> 
> I'm on it. Did you look @ issue #2 on that project

Thank you
